id: A36C59C6E
title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as Ornaments
  of the Practice Lineage'
type: translation
pechas:
- I050D15A8
- IBBA857A7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:37.160425
  last_modified_at: 2023-01-04 13:02:37.160429
  collections:
  - Milarepa Series
  - Works of Tibetan Masters
alignment_to_base:
  I050D15A8/BCA8: 4A80
  IBBA857A7/9F7D: 4A80
